### ISSUE TITLE
Docker for desktop is closed if using built-in k8s cluster there

### ISSUE THREAD

**Issue by twsouthwick** [Azure/Bridge-To-Kubernetes#132]
**Describe the bug**
I initially just enabled the k8s cluster in Docker for Desktop to set up a local cluster for dev purposes. I wanted to be able to use Bridge to Kubernetes to hook into that set up so I could just have a single microservice setup I actually want to debug. However, I get a prompt saying that Bridge to Kubernetes needs to stop process com.docker.backend to free port 443:

![image](https://user-images.githubusercontent.com/583206/208198906-dc15dcec-a973-4300-9fc4-3ebbc1eab23b.png)

**Mention the platform you are using**
VS Code on Windows

**To Reproduce**
1. Enable k8s cluster in Docker for Desktop
2. Deploy project there (can repro easily with todo sample in this repo)
3. Attempt to use the bridge for the stats-api

**Expected behavior**
That it works without shutting docker down

**Desktop (please complete the following information):**
 - OS: Windows 22621.963

**Comment by sabbour** [comment]
The issue seems to be that a Docker process is binding to port 443. Not sure at this point if it is another container or something internal to Docker.

- What is the output of `docker ps`?
- Are you running Docker Trusted Registry? Are you running Docker Universal Control Plane? Both can bind to port 443.

**Comment by sabbour** [comment]
@blars @twsouthwick are the services you're trying to connect to via Bridge also using ports 80 and 443 by any chance?

**Comment by twsouthwick** [comment]
I used the tools sample from this repo without any changes.

**Comment by sabbour** [comment]
@twsouthwick Bridge to Kubernetes is trying to setup a port forward to your existing service on the cluster which clashes with Docker Desktop that is also binding to port 80 locally. That could be Docker Desktop itself or another container running locally. 

Do you mind testing this for me?
1. What's the output of `docker ps` when you're experiencing this issue?
1. Try to change port 80 in the deployment to something else and re-deploy it to the cluster then connect via Bridge again https://github.com/Azure/Bridge-To-Kubernetes/blob/e34119c0500e408c53bff9e763cf617c72717e8c/samples/todo-app/deployment.yaml#L126

**Comment by blars** [comment]
@sabbour The services we are trying to debug in cluster are using port 80.  I've been experimenting with rancher-desktop as a docker-desktop replacement for the past few days so I don't have an active docker-desktop cluster.  Rancher-desktop seems to run as well as docker-desktop (if not a little better), and BTK seems to work great.

I think our biggest complaint going forward is that BTK targets services instead of deployments, so if we have multiple versions of a service running, we can't target a specific one.

**Comment by sabbour** [comment]
@blars can you elaborate a bit on what you mean by multiple versions of a service running? How does this look like from the perspective of what's deployed on Kubernetes and how do you route traffic to the right service without Bridge to Kubernetes?

**Comment by blars** [comment]
@sabbour Sorry, didn't mean to hijack this issue...I can always open a separate enhancement request.

We use Istio as our service mesh, which allows us to have a single service that can target multiple deployments based on some criteria in Istio's VirtualService and DestinationRule resources (more or less what k8s is currently building out with their Gateway API).

Telepresence has the ability to target the deployment (ie, service-a-v1 or service-a-v2) instead of the service (service-a) in cases where we have more than one version of an existing service.

Honestly, this isn't that big of an issue for us since we don't tend to have multiple versions when running in a local environment like docker-desktop or rancher-desktop, it's only an issue for environments we have hosted in a cloud provider like AKS, GKE, etc.

**Comment by elenavillamil** [comment]
Hi everyone, this is related to the ports the services in your cluster use. The way bridge works is by setting port forwarding so when user debugs local service can behave like it is running in the cluster. In this case docker is been killed because it is been recognized as a service that is using some of the ports that Bridge has to set up port forwarding on (again this ports comes directly from your cluster/deployment config). I have installed dokcer for desktop on my windows machine and I indeed can repo with our todo sample app. After sometime I realized that it is the port from a loadbalancer service that would cause this issue (I changed all the ports and in below screenshot message only complains about port from the loadbalancer serivce). It seems to me that if the docker k8s cluster has a service deployed marked as loadbalancer, then it inheritately becomes a port used by Docker. 
<img width="1030" alt="Screenshot 2023-01-26 at 3 32 27 PM" src="https://user-images.githubusercontent.com/4663400/214974438-86120287-d534-4707-b54e-517d8252339a.png">

Not sure if it is some automatic binding or port forwarding that Docker sets up? I have been doing some reading to try and figure out why, and I ran into [this](https://www.docker.com/blog/dockershim-not-needed-docker-desktop-with-kubernetes-1-24/#:~:text=Docker%20Desktop%20automatically%20binds%20network%20ports%20on%20the,remembering%20internal%20IP%20addresses%20or%20reconfiguring%20their%20DNS.)
"Docker Desktop automatically binds network ports on the host and tunnels traffic to Kubernetes, allowing developers to immediately interact with their applications without remembering internal IP addresses or reconfiguring their DNS."

I will keep doing some research and see if there is a way around it, but wanted to post findings here just in case it gets some ideas going from other people.

**Comment by sabbour** [comment]
@twsouthwick was the stats-api service by any chance already running on your Docker Desktop local installation Kubernetes cluster? So in that case, it is running locally on port 80 and you're trying to use Bridge to Kubernetes to portforward it also to port 80 on your machine?

**Comment by twsouthwick** [comment]
Yes, I had deployed it per the instructions and it was running in kubernetes. I then tried to debug a local build of it with the bridge to kubernetes tooling.

**Comment by sabbour** [comment]
This seems to be a known behavior of Docker Desktop (https://www.docker.com/blog/how-docker-desktop-networking-works-under-the-hood/) where the Docker API proxy forwards requests from the host to the VM via vpnkit and binds the container ports to the host machine. I don't know of a workaround or a configuration that can change this.

In the meantime, minikube, kind, or rancher-desktop are alternatives.
