### ISSUE TITLE
Migrate from Newtonsoft to System.Text.Json

### ISSUE THREAD

**Issue by Eneuman** [Azure/Bridge-To-Kubernetes#134]
I was wondering if you would be intrested in a PR where Newtonssoft is removed and System.Text.Json is used instead?
I did this work today and my build seems to working fine.

Logging is not working at the moment because of a internal bug in System.Text.Json. I have a issue open and I'm hoping that they can backport the fix from .Net 7 to .Net 6 otherwise more changes are needed.

Since JsonPatch is not in .Net yet, I had to replace "Microsoft.AspNetCore.JsonPatch" with "SystemTextJsonPatch" and it seems to be working fine.

There are a few more things that i'm going to try out:
* Move away from individual package dependencies and instead use Frameworks dependency.
* Replace Portable.BouncyCastle and instead use the new certificate functions in .Net 6.
* Move from Autofact to the build in DI in .Net core.
* Move from old Microsoft.Azure.Management.ResourceManager.Fluent and instead use the new Azure SDKs
* Move to .Net 7.

My main goal is to try and AOT compile the devhosagent and the restore job. I have a feeling that the debug startup performance gain from this will be huge.

I love B2K so If you want me to make a PR for any of the above, just let me know.

**Comment by elenavillamil** [comment]
Hi @Eneuman. Of course. We welcome contributions and the STJ work is something that is on backlog already, so it sounds great. The other work you mentioned sounds interesting as well and we would be happy to help review and test. We are also happy to help if you have any questions along the way. Just know we have a small team supporting this project, so your PR/questions may take some time to get merged/answer. This not lack of interest, just us trying to keep up with all streams of work.

Thank you!

**Comment by Eneuman** [comment]
@elenavillamil Ok, I will start working on a PR for moving to STJ. I have already done the job localy and tested the work for awbout 2 week but would like some information regarding how to test the endpoint manager localy.
Should I just replace the files in the extention catalog or can I build the .vsix extension and install it localy?
When is the "localagent" used?

**Comment by elenavillamil** [comment]
@Eneuman first thank you for your contributions.

For testing steps, there will be a few things you need to update:
- For CLI you can check steps [here](https://github.com/Azure/Bridge-To-Kubernetes/tree/main/src/dsc). Basically once you run dotnet build and dotnet publish all you have to do is set BRIDGE_BUILD_PATH environment variable to the path with the build/publish output. 
- Since this change is in common and it will also affect images (restoration job - BRIDGE_RESTORATIONJOBIMAGENAME, [devhost agent](https://github.com/Azure/Bridge-To-Kubernetes/tree/main/src/devhostagent) - BRIDGE_DEVHOSTIMAGENAME and [routingmanager](https://github.com/Azure/Bridge-To-Kubernetes/tree/main/src/routingmanager) - BRIDGE_ROUTINGMANAGERIMAGENAME) you would want to build those and upload them to you local registry, then set environment variables to override them (I added environment variable to override each on next to the name). I also link readmes for each images which has image building steps. 
- Open VS from the terminal where you set the environment variables and you should be all set to go (at this point it will be all your code). 

Let me know if you have additional questions.

**Comment by elenavillamil** [comment]
@Eneuman first thank you for your contributions.

For testing steps, there will be a few things you need to update:

For CLI you can check steps [here](https://github.com/Azure/Bridge-To-Kubernetes/tree/main/src/dsc). Basically once you run dotnet build and dotnet publish all you have to do is set BRIDGE_BUILD_PATH environment variable to the path with the build/publish output.
Since this change is in common and it will also affect images (restoration job - BRIDGE_RESTORATIONJOBIMAGENAME, [devhost agent](https://github.com/Azure/Bridge-To-Kubernetes/tree/main/src/devhostagent) - BRIDGE_DEVHOSTIMAGENAME and [routingmanager](https://github.com/Azure/Bridge-To-Kubernetes/tree/main/src/routingmanager) - BRIDGE_ROUTINGMANAGERIMAGENAME) you would want to build those and upload them to you local registry, then set environment variables to override them (I added environment variable to override each on next to the name). I also link readmes for each images which has image building steps.
Open VS from the terminal where you set the environment variables and you should be all set to go (at this point it will be all your code).
Let me know if you have additional questions.
