### ISSUE TITLE
Unable to debug the database API in the todo sample app for the second time

### ISSUE THREAD

**Issue by aforank** [Azure/Bridge-To-Kubernetes#186]
**Describe the bug**
When I debug the database api in todo sample app for the first time, it works fine. However when I stop the debugging, and restart the debug session again I get this error

![image](https://user-images.githubusercontent.com/19813442/223085926-f49f3390-30f6-436d-8cb7-56518e9ea557.png)

**Mention the platform you are using**
Visual Studio Enterprise 2022 (version 17.5.0)

**To Reproduce**
1. Create a B2K profile for database api
2. Click on debug
3. Stop the debugging
4. Click on debug again

**Expected behavior**
The debug session should run as it did for the first time

**Workaround**
Delete the database-api-restore job running in the cluster manually.

**Additional context**
Please change the Target framework version to net6.0 before re-producing the issue, otherwise you may get a different error

Reach out directly at anks@microsoft.com for any queries.

**Comment by hsubramanianaks** [comment]
@aforank This is expected behavior , restoration pods from your previous debug session is still terminating, until that is completed this message will appear. please refer below for more details. Please let us know if this is a different issue or if this message is showing consistent. Thank you. 
https://github.com/Azure/Bridge-To-Kubernetes/pull/136

**Comment by aforank** [comment]
Thanks. As mentioned, it worked after a couple of minutes post restoration pod was terminated. I would recommend to change the error message accordingly, so that it is clear for the end-user that it may take a minute to gracefully terminate.

Closing the issue.
