### ISSUE TITLE
Allow overriding of service environment variables

### ISSUE THREAD

**Issue by adibradfield** [Azure/Bridge-To-Kubernetes#194]
I am looking to use this extension to improve the debugging experience of our existing services. Me and a few other developers use WSL for development. After reading the docs about the suggested way to enable this workflow, we didn't really like the idea of having to update all our microservices to use environment variables for getting host names and ports, just to enable a handful of developers, so we came up with another solution. 

We run [kubefwd](https://github.com/txn2/kubefwd) on our WSL instance, and then lie to BridgeToKubernetes and set `useKubernetesServiceEnvironmentVariables` to `true`. Our apps can then continue to use the host names that we set in our config files instead, rather than relying on env variables. 

An issue has come up though, where we have the need to override one of the service environment variables for a specific application. If we set a value for it in the `KubernetesLocalProcessConfig.yaml` file, it gets overridden.

Would it be possible to make the config file take precedence over the service environment variables, or alternatively add a way to disable the behaviour of adding those env variables so that that value won't get overridden?

**Comment by elenavillamil** [comment]
@adibradfield, thank you for this issue. This is a great out of the box way of using bridge :) Yes we will add this to our planning and loop our engineer and PM to discuss how to enable this scenario for your team. For timeline, just keep in mind we are a small team. We also welcome contributions, so please feel free to be involved on the discussion and even implementation if you are up for it :) 

Some dev notes:
Code where environment variables are populated is here:
https://github.com/Azure/Bridge-To-Kubernetes/blob/bcec98c4bf016d7788e020bcbb7f417a9c729cd5/src/library/Connect/LocalEnvironmentManager.cs#L423

Some implementation ideas:
- One option would be to pass user defined environment variables here and ensure they take precedence. 
- Other option would be having an alternate mode to useKubernetesServiceEnvironmentVariables for WSL that assumes user has set up kubefwd and hence bridge can skip setting up environment variables.

Currently leaning towards second option since it seems more targeted to the scenario.

Cc: @hsubramanianaks, @Tatsinnit, @Eneuman as fyi. Thoughts and input welcomed :)

**Comment by hsubramanianaks** [comment]
@adibradfield Hi Adrian - Any update on the above approach? please let us know. Thank you.

**Comment by hsubramanianaks** [comment]
@adibradfield Please reopen this issue if you need further assistance on this. Also, if you have bandwidth, you can always contribute to this feature request. Thank you.
