### ISSUE TITLE
File Path issue with Linux containers being debugged on Windows Dev workstations. 

### ISSUE THREAD

**Issue by Dragonsong3k** [Azure/Bridge-To-Kubernetes#274]
**Describe the bug**
Not sure this is the right place for this.

I have a ASP.NET Core 6 Application that runs on K8s in a linux container. 
When debugging using B2K, .NET converts the file paths from /mnt/somedir to C:\mnt\somedir.
This is by design for .NET but I thought that B2K would intercept this and refer to the paths as they would be in the cluster and use the storage that is mounted in the cluster.

This makes using B2K to debug a bit difficult as frequent FileNotFound exceptions occur due to the translation. 

I'm thinking this is something I am doing wrong and need to provide extra configs to B2K? 

Any help would be appreciated.

**Mention the platform you are using**
Using VSCODE for debugging.

**Desktop (please complete the following information):**
 - OS: Windows 11

**ASP.NET Core 6 Application running in AKS cluster in Linux container**

**Comment by hsubramanianaks** [comment]
@Dragonsong3k Thanks for raising this issue. I think you are trying to use volume mounts from your k8s cluster via bridge. Please correct me If I am wrong. yes you do need to define them in [kuberneteslocalprocessconfigyaml](https://learn.microsoft.com/en-us/visualstudio/bridge/configure-bridge-to-kubernetes#local-configuration-using-kuberneteslocalprocessconfigyaml) so that the volumes are downloaded to your local which your application can refer during the debugging process. If you are already doing this and facing problems, please share all the logs from ```/tmp/Bridge To Kubernetes``` folder. Thank you.

**Comment by Dragonsong3k** [comment]
Sorry for the late response. I will try using the config yaml. Is it ok to assume that the paths will be translated from Windows format to Linux format?

**Comment by hsubramanianaks** [comment]
@Dragonsong3k No problem, here is how it works basically b2k uses ```kubectl cp``` command to download/copy the volumes from the cluster to your local. if it is windows, it does create a temp directory and downloads the volumes but any other platform it would use the same path as the one specified in config yaml. I am curious why would you expect paths to be translated? If you are using windows, it would be a temp directory created by b2k. Please let me know how it goes or further questions.

**Comment by hsubramanianaks** [comment]
@Dragonsong3k Please reopen this issue if it still happens. Thank you.
