### ISSUE TITLE
XDG Specification for the bridge folder

### ISSUE THREAD

**Issue by untainsYD** [Azure/Bridge-To-Kubernetes#323]
On linux this plugin creates `$HOME/.bridge` folder, and it is an ignorance of XDG specification, it should create that folder in `$XDG_CONFIG_HOME` to fit the specification.
I am the user, that trying to fit this specification and this plugin ignores it.

Also, it may be an env variable or VSCode plugin setting to set the path for the `.bridge` folder.

**Comment by devholland** [comment]
Hello, this issue got marked as completed, that means we can move the `~/.bridge` folder somewhere else now? How can this be done?

**Comment by hsubramanianaks** [comment]
@devholland @untainsYD we closed all the older issues which didn't had any response from OP, this issue was closed by mistake, apologies for it. I am reopening it and we need more details about what the request is for? 

so, if I am understanding correctly, you are using linux with XDG specifications and want to specify different folder or directory name for ```$HOME/.bridge``` as env variable ? we also want to know what is issue or error happening if this is not set correct ? Please let us know. Thank you.

**Comment by devholland** [comment]
Hi @hsubramanianaks, I would like to clean up my $HOME directory according to the XDG specifications. Almost all of the programs I'm using can be configured this way, usually by setting an environment variable.

Only very few apps can not be configured this way and this is unfortunately one of them. There is no error happening with the `~/.bridge` folder, it is just a question of being able to have a more modern and cleaned up $HOME directory. I don't particularly care about the `~/.bridge` folder and having it stored away in `.local/share` or `.cache` would be one step more of having a XDG conforming system.

**Comment by untainsYD** [comment]
> so, if I am understanding correctly, you are using linux with XDG specifications and want to specify different folder or directory name for `$HOME/.bridge` as env variable ? we also want to know what is issue or error happening if this is not set correct ? Please let us know. Thank you.

I don't have any errors, only folder `~/.bridge` in my home directory instead of `.config/bridge` or `.config/cache/bridge`, etc. I would like this folder to be in fit with XDG specification on linux, instead of putting it in `home` directory.
