### ISSUE TITLE
Bridge to kubernetes for a DAPR microservice

### ISSUE THREAD

**Issue by jmtramullas** [Azure/Bridge-To-Kubernetes#63]
Hello.,

I'm debugging my microservices backend inside minikube successfully using Bridge-to-Kubernetes. This backend is build using dapr. Each microservice invoke the other ones using a sidecar container in the same pod, which takes care of the communication between microservices.

I reach a trouble in debug with bridge to kubernetes, relative to dapr sidecar. I cannot launch dapr service invocation from my app using dapr sidecar, because it cannot found it at default port (3500).

Because of the execution moves to VS Code when using Bridge-to-Kubernetes, this sidecar is not accessible from this other debugging environment.

So, my question is the following: Do you how how can I make this call between my service-app and its dapr-sidecar, in this debugging environment?

Thanks in advance!
Joan Miquel

**Comment by elenavillamil** [comment]
@jmtramullas, thank you for the detailed issue. Couple questions, are you using bridge on isolation mode or without isolation? And have you already check steps here: [Bridge to Kubernetes support for Dapr services | Dapr Docs](https://v1-2.docs.dapr.io/developing-applications/debugging/bridge-to-kubernetes/#:~:text=Debug%20Dapr%20apps%20locally%20which%20still%20connected%20to,of%20debugging%20is%20often%20called%20local%20tunnel%20debugging.) Just wanted to run those questions before debugging further.

**Comment by jmtramullas** [comment]
Hello @elenavillamil. Thanks for your response.
I'm using bridge without isolation mode.
I reached this forum after browsing on many other ones, as dapr, which recommended me put my question in your forum.

**Comment by elenavillamil** [comment]
Hi @jmtramullas, apologies for the delay response. Could you provide the bridge logs for your run and a bit more detail description of the issue and expected behavior. For example can bridge connect but the break point is not hit or does bridge fail to connect all together? What service are you debugging locally? Are you trying to start the dapr sidecar locally?

**Comment by elenavillamil** [comment]
@jmtramullas I am closing this issue due to inactive but if you are still running into this please reach out. I will say, when DAPR is enabled bridge will always assume the target container of the pod is the service itself not the DAPR sidecar. In other words, bridge does not support debugging the DAPR sidecar itself. If you are using bridge to debug your app, you should still be able to connect to the dapr side car (which will remain in the pod in the cluster).
