### ISSUE TITLE
Missing environment variables for services with multiple ports

### ISSUE THREAD

**Issue by acosoft** [Azure/Bridge-To-Kubernetes#64]
**Describe the bug**

My bridge is configured with `"useKubernetesServiceEnvironmentVariables": true`. and I have a service that exposes two ports. 

Ports are forwarded to "random" port on local machine and variables are exposed in the form `<service_name>_SERVICE_<port>_PORT`.

There is no way for me to know the name of the variable before I start the bridge. 

**Mention the platform you are using**
I use vscode and cluster is configured in Google Cloud.

**To Reproduce**
1. deploy service with multiple ports, let say it is named TEST, with ports A=8080 and B=9090
2. Configure bridge in vscode without local launch cofiguration
3. set `"useKubernetesServiceEnvironmentVariables": true` in tasks.json
4. connect to cluster
5. in the Bridge Menu, select Show connection diagnostics information
6. check if there is a variable TEST_SERVICE_PORT_A or TEST_SERVICE_PORT_B (there are not set)

**Expected behavior**
Environment variables should be named <service_name>_SERVICE_PORT_<port_name>

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser chrome
 - Version 106.0.5249.61 (Official Build) (64-bit)

**Comment by elenavillamil** [comment]
Hi @acosoft, the name of the variable names are not random, they follows [Kubernetes service environment variables rules] (https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables). The environment variables wont show up on the bridge menu, but they are accessible to your service running locally. Example below. Please let me know if you still have questions. If not I will close this in the new few days.


<img width="1358" alt="Screenshot 2022-12-14 at 4 13 13 PM" src="https://user-images.githubusercontent.com/4663400/207715362-5723abd6-1135-49be-a076-c9b4a9f40578.png">

**Comment by elenavillamil** [comment]
Hi, closing this item due to inactivity. Please feel free to re-open if above response does not fully address your question/issue.

**Comment by Strayfe** [comment]
> so you wont see TEST_SERVICE_PORT_A or TEST_SERVICE_PORT_B - you will only see TEST_SERVICE_PORT

I am confused as to why this would be the case as Kubernetes supports multiple ports per service and there seems to be a few discrepancies between the way that Kubernetes and Bridge allocate ports from the service.

There are environment variables created by Kubernetes that reference ports by the **name** metadata, if it exists, instead of by port which are allocated arbitrarily when using Bridge as the OP described.

Say your microservice has a dependency on a service you have no control over, let's use the bitnami RabbitMQ helm chart  as an example, which exposes the following service (trimmed for brevity): 

```
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: amqp
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: epmd
  - name: dist
    port: 25672
    protocol: TCP
    targetPort: dist
  - name: http-stats
    port: 15672
    protocol: TCP
    targetPort: stats
``` 

This service has 4 ports described, all with `name` metadata so the ports can be referenced by name in other resources like Ingresses, etc.

An example of this would look like: 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
...
spec:
  rules:
  - host: rabbitmq.regtransfers.dev
    http:
      paths:
      - backend:
          service:
            name: rabbitmq
            port:
              name: http-stats        <-- port referenced by name, not port number
```

Now, when we look at one of our RabbitMQ pods in a Kubernetes cluster, we can see environment variables that have been created to reflect each of these ports by **name** (IP addresses obfuscated to 0.0.0.0):

```
<<K9s-Shell>> Pod: rabbitmq/rabbitmq-0 | Container: rabbitmq 
I have no name!@rabbitmq-0:/$ printenv | grep RABBITMQ_
RABBITMQ_PORT_5672_TCP_ADDR=0.0.0.0
RABBITMQ_PORT_15672_TCP_ADDR=0.0.0.0
RABBITMQ_PORT_5672_TCP_PORT=5672              <-- (c)
RABBITMQ_PORT_4369_TCP_PORT=4369
RABBITMQ_SERVICE_PORT_AMQP=5672               <-- (d)
RABBITMQ_PORT_25672_TCP_ADDR=0.0.0.0
RABBITMQ_PORT_5672_TCP_PROTO=tcp
RABBITMQ_PORT_4369_TCP=tcp://0.0.0.0:4369
RABBITMQ_PORT_25672_TCP_PORT=25672
RABBITMQ_SERVICE_PORT=5672                    <-- (b)
RABBITMQ_SERVICE_PORT_DIST=25672
RABBITMQ_PORT_25672_TCP_PROTO=tcp
RABBITMQ_PORT_4369_TCP_ADDR=0.0.0.0
RABBITMQ_SERVICE_HOST=0.0.0.0                 <--- (a)
RABBITMQ_PORT=tcp://0.0.0.0:5672
RABBITMQ_SERVICE_PORT_HTTP_STATS=15672
RABBITMQ_PORT_15672_TCP_PROTO=tcp
RABBITMQ_PORT_25672_TCP=tcp://0.0.0.0:25672
RABBITMQ_SERVICE_PORT_EPMD=4369
RABBITMQ_PORT_5672_TCP=tcp://0.0.0.0:5672
RABBITMQ_PORT_15672_TCP_PORT=15672
RABBITMQ_PORT_15672_TCP=tcp://0.0.0.0:15672
RABBITMQ_NODE_NAME=rabbit@rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cluster.local
RABBITMQ_PORT_4369_TCP_PROTO=tcp
```

So, if I wanted to reference my RabbitMQ instance using these environment variables I would take (a) and ideally (b) in my code and allow Bridge to update the variables accordingly:

![image](https://user-images.githubusercontent.com/642269/217798974-b8c13cdf-a603-4d32-956f-e25556132edf.png)

However, we run into the issue where only the last registered port (in order) will be allocated to the `RABBITMQ_SERVICE_PORT` variable as seen below: 

![image](https://user-images.githubusercontent.com/642269/217801052-c48a2795-38a5-499b-ac68-87d1779491b8.png)

In the above image you can see:
(1) - 4x ports mapped, same as in the service but randomly allocated ports on my dev machine
(2) - the last registered port has been allocated to the `RABBITMQ_SERVICE_PORT` variable

There are a few issues here:
As you can see from (b), Kubernetes has mapped the `RABBITMQ_SERVICE_PORT` correctly to the AMQP port (first in the collection) whereas Bridge has allocated the last port in the collection to the variable which is not the AMQP port so I get connection errors in code.

Also, as there is no way to pre-determine what port Bridge is going to allocate to (c) when it creates its proxy ports and therefore creates the names for the variables, we cannot use any of the values listed here in our code.

Now, you might have noticed at this point that there is a discrepancy highlighted by the existence of (d) which is a port variable declared in Kubernetes using the name metadata instead of a port which would be easier to track in code as we could just request the `RABBITMQ_SERVICE_PORT_AMQP` port and then no matter what port Bridge chose to use for its proxies, we could track it.

I am not sure why Bridge does not fetch this variable from the cluster but could it be looked into?
