### ISSUE TITLE
Failed to launch endpoint manager

### ISSUE THREAD

**Issue by SteveCurran** [Azure/Bridge-To-Kubernetes#96]
Receive error when debugging in vscode on linux with latest version of b2k, unable to launch endpoint manager

vscode ubuntu 20.04

Bridge to Kubernetes initialization (VS Code v1.73.1 - Extension v1.0.120221031)
Logs: /home/steve/.config/Code/logs/20221110T145302/window1/exthost/mindaro.mindaro/mindaro-vscode-2022-11-10T20-53-08.103Z.txt
Waiting for EndpointManager to come up ...
An unexpected error occurred: 'Failed to launch EndpointManager.'
To see our active issues or file a bug report, please visit https://aka.ms/bridge-to-k8s-report.
For diagnostic information, see logs at '/tmp/Bridge To Kubernetes'.
Failed to establish a connection. Error: An unexpected error occurred: 'Failed to launch EndpointManager.'
To see our active issues or file a bug report, please visit https://aka.ms/bridge-to-k8s-report.
For diagnostic information, see logs at '/tmp/Bridge To Kubernetes'.

[bridge-mindarocli-2022-11-11-18-46-33-205421.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/9992741/bridge-mindarocli-2022-11-11-18-46-33-205421.txt)

**Comment by hsubramanianaks** [comment]
@SteveCurran Thanks for the details. Usually in Linux/WSL2 , set --use-kubernetes-service-environment-variables to true, I don't see that in the logs. Can you try setting this and see if it works? EndpointManager is intended for Windows and Mac, B2K uses environment variables for Linux. Please let me know.

**Comment by SteveCurran** [comment]
@hsubramanianaks I have been using b2k on linux for quite a while and have never been required to have use-kubernetes-service-environment-variables set to true.  The previous version of b2k works with it set to false and uses the endpoint manager without a problem. When setting it to true endpoint manager is not launched and I am no longer able to connect to other services  running in my local cluster during debugging, I connect using the service dns names like ***.***.svc.cluster.local

**Comment by hsubramanianaks** [comment]
@SteveCurran Thanks for the details. Since most of us here use WSL2 or Linux on Virtual Machines, VSCode always asks us to set use-kubernetes-service-environment-variables to true always since it is considered remote development. I will see if there anyway to reproduce this. Also I have tested the latest b2k with vscode with use-kubernetes-service-environment-variables to true and I don't see any issues connecting to services in the cluster. Can you provide more details on svc.cluster.local ? Thanks.


<img width="418" alt="image" src="https://user-images.githubusercontent.com/105889062/201997689-72b4302c-e6d1-4717-a75b-843ea76fe2ef.png">

**Comment by SteveCurran** [comment]
@hsubramanianaks I am running everything  within ubuntu 20.04 virtual machine, this includes vscode and a local k3s cluster.  So not really remote development. So it appears that if the endpoint manager is not running when setting the use-kubernetes-service-environment-variables to true, then I cannot connect to a service using service.namespace.svc.cluster.local as a service url.  It appears that the dns name does not get resolved when not running the endpoint manager, it does get resolved when running the endpoint manager. I am not familiar with the details of what exactly the endpoint manager does but from my understanding it forwards requests to the appropriate container running in the cluster.

**Comment by elenavillamil** [comment]
When endpoint manager runs we can update etc/hosts and that is what allows the dns resolution. When using use-kubernetes-service-environment-variables we no longer edit etc/hosts (since it needs elevated access) and we instead use kubernetes environment variables. For the short term while we fix this bug if you build your URL using <SERVICE NAME>_SERVICE_HOST, <SERVICE>_SERVICE_PORT environment variables it should work. More details on kubernetes service environment variables: https://learn.microsoft.com/en-us/visualstudio/bridge/kubernetes-environment-variables

This bug means we need to update our manual testing that Joyer runs before releases to account for fully Linux based system. Meaning when VSCode runs natively on linux instead of using remote debuging capabilities.

@SteveCurran, the folder where you found the CLI log you provided should have other logs (library and endpoint manager logs), could you share all of them for the run that fails? We will also try to reproduce on our end.

Thank you and sorry for the inconvenience.

**Comment by hsubramanianaks** [comment]
@SteveCurran if this issue is still happening, can you share the logs which has title bridge-library-* etc.. that would show exactly why endpoint manager failed to launch. Thank you.

**Comment by SteveCurran** [comment]
@hsubramanianaks Ok running the latest version endpoint manager fails to launch. Attached are the logs.

[bridge-mindarocli-2022-12-03-18-14-54-140688.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/10147085/bridge-mindarocli-2022-12-03-18-14-54-140688.txt)
[bridge-mindarocli-2022-12-03-18-15-10-140765.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/10147086/bridge-mindarocli-2022-12-03-18-15-10-140765.txt)
[bridge-library-2022-12-03-18-15-10-140765.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/10147087/bridge-library-2022-12-03-18-15-10-140765.txt)

**Comment by dsu-igeek** [comment]
This had been working fine for me and suddenly it stopped.  I tracked it down to the EndpointManager not starting.  From the log files, the startup command is:

`pkexec env HOME="/home/username/" bash -c "\"/home/username/.config/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/EndpointManager/EndpointManager\" \"username\" \"/home/username/.bridge/EndpointManager/EndpointManagerSocket\" \"/tmp/Bridge To Kubernetes\" \"24edd896-9315-4a85-8669-e72c3f7e394b1670437460628:889add9078ee:6e16409fd4c9:7c52be88bd9a\" &> /dev/null &"`

If I run that command (without the redirect of logs to /dev/null, I get:

`A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/username/.config/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/EndpointManager/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET Core runtime can be found at: https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=centos.8-x64`

I think the problem here is that pkexec discards all of the environment variables before running the app.  If I run it as:
`pkexec env HOME="/home/username/" DOTNET_ROOT="/home/username/.config/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet" bash -c "\"/home/dsmithuchida/.config/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/EndpointManager/EndpointManager\" \"username\" \"/home/username/.bridge/EndpointManager/EndpointManagerSocket\" \"/tmp/Bridge To Kubernetes\" \"043b0eee-350a-4b34-9d4c-47aceb42a9411670434959609:dd921c126929:13a200f83cbe:8d5f0e1bf472\""
`
endpoint manager starts fine and I can use it.

 I believe this code in ./src/library/EndpointManagement/EndpointManagementClient.cs is where it actually builds the command line
`                        // Try to use pkexec to show a GUI prompt for the user's password so we can run EndpointManager as root.
                        // If we are already running as root, then pkexec will not show a prompt.
                        // When running in Codespaces the user is setup to run sudo without needing to enter password.
                        fileName = _environmentVariables.IsCodespaces ? "sudo" : "pkexec";
                        command = $"env HOME=\"{_fileSystem.HomeDirectoryPath}\" bash -c \"{quotedLaunchPathAndArguments} &> /dev/null &\"";
`
That code has not changed in some time.  I don't understand why this worked before, my guess is either pkexec was updated or something changed in VSCode such that it started using pkexec. I'm not a big VSCode user, is it possible I had isCodespaces set before?

I think this is fixable by altering the command line.  I'd try it out on my machine ad submit a PR but I don't understand how to build this so I can install into vscode.

**Comment by elenavillamil** [comment]
@dsu-igeek thank you for the details. This is very useful. We are able to reproduce EndpointManager not starting when using VSCode running natively on WSL. Our team will prioritize looking and fixing this as part of our next work. Did you ever got to try the fix by altering command line? To test changes to CLI you can follow steps [here](https://github.com/Azure/Bridge-To-Kubernetes/tree/main/src/dsc) under building section to build and publish your new CLI and then set BRIDGE_BUILD_PATH environment variable to your new published version. Something like this:
export BRIDGE_BUILD_PATH='/Users/elvilla/projects/Bridge-To-Kubernetes/src/dsc/bin/Debug/net6.0/osx-x64/publish/'. Open VSCode after setting the variable and you will be using your newly built CLI instead of the production one.

**Comment by hsubramanianaks** [comment]
@dsu-igeek Thanks for your detailed analysis, but I see different behavior from @SteveCurran logs. DOTNET_ROOT will be set by vscode extension while invoking B2K CLI and here the code [reference](https://github.com/Azure/vscode-bridge-to-kubernetes/blob/473c44b4a03ca9e61dcaf42552d2980886d30fee/src/clients/BridgeClient.ts#L299). Also from Steve logs I can see DOTNET_ROOT is set and it failed with different error **"cannot assign requested address".**

Also B2K code set's environment variables at line 442 [here](https://github.com/Azure/Bridge-To-Kubernetes/blob/main/src/library/EndpointManagement/EndpointManagementClient.cs#L442) ,  pkexec is executed after setting both launch path and env variables map at line 448 [here](https://github.com/Azure/Bridge-To-Kubernetes/blob/main/src/library/EndpointManagement/EndpointManagementClient.cs#L448) But unfortunately, we don't have logs for platform.execute method (which can be added). But from the logs I can see exit code was zero.

<img width="769" alt="image" src="https://user-images.githubusercontent.com/105889062/214235776-4cba8167-c68b-45f3-ad4c-adee0474a833.png">

```
2022-12-03T18:15:12.3418033Z | Library | TRACE | Launch EndpointManager: pkexec env HOME="/home/steve/" bash -c "\"/home/steve/.config/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/EndpointManager/EndpointManager\" \"steve\" \"/home/steve/.bridge/EndpointManager/EndpointManagerSocket\" \"/tmp/Bridge To Kubernetes\" \"3b437b7a-6275-4baf-9798-80378329204b1670090726007:30e458a9b177:3137de46904d:ad83af63a3c9\" &> /dev/null &"
2022-12-03T18:15:12.3421370Z | Library | TRACE | 'DOTNET_ROOT' environment variable with '/home/steve/.config/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet' while launching 'EndpointManager'.
2022-12-03T18:15:12.3449894Z | Library | TRACE | Launch output: Waiting for process 140791
2022-12-03T18:15:19.6996816Z | Library | TRACE | Launch output: Process has exited with exit code 0
2022-12-03T18:15:19.7025444Z | Library | TRACE | Waiting for EndpointManager to come up ...\n
2022-12-03T18:15:19.7040826Z | Library | TRACE | Connecting to EndpointManager
2022-12-03T18:15:19.7685818Z | Library | TRACE | EndpointManager is not running: 'Cannot assign requested address /home/steve/.bridge/EndpointManager/EndpointManagerSocket'
```

@SteveCurran  did it prompt you to enter password  in the terminal to run it as root ? if this step is missing it would not launch endpoint manager. please let me know to further proceed on this. Thank you.

**Comment by SteveCurran** [comment]
@hsubramanianaks Yes it prompts to enter the password to run as root.

**Comment by SteveCurran** [comment]
@hsubramanianaks I tried the latest version and that seems to fix the problem. Thanks for the help.
